[project]
name = "ldr-nightlight"
board = "arduino-uno"
version = "0.2"

[[component]]
id = "ldr1"
type = "photoresistor"

[[component]]
id = "led1"
type = "led"
color = "yellow"

[[wire]]
from = "board.A0"
to = "ldr1.out"

[[wire]]
from = "board.D13"
to = "led1.a"

[code]
src = "src/main.ino"
